# vi keybindings
bindkey -v
# set default editor for shell
export EDITOR=nvim
export VISUAL=nvim

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#ohmyzsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git docker aws docker-compose kubectl helm)
source $ZSH/oh-my-zsh.sh
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# add aliases
if [ -f ~/.aliases ]; then
. ~/.aliases
fi

### add to PATH
export PATH=$PATH:~/go/bin
export PATH=$PATH:$HOME/.pulumi/bin
export RIPGREP_CONFIG_PATH=$HOME/.ripgreprc
export PATH=$PATH:$HOME/bin
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
source $HOME/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
. /usr/share/autojump/autojump.sh
export PATH=$PATH:/usr/local/go/bin
#source <(kubectl-argo-rollouts completion zsh)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source $HOME/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"


####### FUNCTIONS #######

# Create a new directory and enter it
mkd() {
        mkdir -p "$@"
        cd "$@" || exit
}

# terragrunt configuration
tg() {
    if [ -z "$1" ]; then
        echo "Use correct second argument: apply/destroy/plan/etc"
    else
        if [ "$1" = "0all" ]; then
            terragrunt destroy -auto-approve && terragrunt apply -auto-approve
        elif [ "$1" = "0apply" ]; then
            terragrunt apply -auto-approve
        elif [ "$1" = "0destroy" ]; then
            terragrunt destroy -auto-approve
        elif [ "$1" = "0fmt" ]; then
            terragrunt hclfmt --terragrunt-check
        else
            terragrunt "$@"
        fi
    fi
}

# history | grep something
his() {
  history | grep $1
}

#xclip function to copy a file into clipboard
function copypaste() {
  cat "$1" | xclip -selection c
}

# terragrunt plan with path
function tgp() {
  terragrunt plan --terragrunt-config $1
}

# terragrunt apply with path
function tga() {
  terragrunt apply --terragrunt-config $1
}

function awslogin() {
  aws sso login --profile $1
}

function awsprofile() {
  export AWS_PROFILE=${1:-default}
}

function awsvaultexec() {
  unset AWS_VAULT
  aws-vault exec $1 --duration 5h
}
